apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: workload
  region: ap-south-1

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: workload-sa
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: workload-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 2
