= Readme

Launch EKS cluster using `eksctl`, Install a workload into cluster via ALB Ingress.

You need to install

. https://kubectl.docs.kubernetes.io/[kubectl]
. https://helm.sh/[helm]
. https://github.com/aws/aws-cli[aws-cli]
. https://eksctl.io/[eksctl]

Post cluster launch, but before launching a sample workload application, to enable external access (Ingress/LoadBalancer), we install Ingress CRDs & also AWS LoadBalancer Controller.

NOTE: This is AWS LoadBalancer, not Application LoadBalancer. AWS LoadBalancer is refers to all load balancers supported by AWS. They include L7 Application LoadBalancer (ALB), L4 Network LoadBalancer (NLB) & Elastic LoadBalancer (ELB). In otherwords, AWS LB ≠ ALB, AWS LB = ALB/NLB/ELB.

== Quasi-Declarative version

=== Create cluster

[source,shell]
----
eksctl create cluster -f eksctl-workload-cluster.yml
----

=== Install Ingress CRDs

[source,shell]
----
# to know what gets created, without applying them explicitly
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master" --dry-run='server'

kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
----

=== Install AWS Load Balancer Controller

[source,shell]
----
helm repo add eks https://aws.github.io/eks-charts

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
    -n kube-system \
    --set clusterName=workload \
    --set serviceAccount.create=false \
    --set serviceAccount.name=workload-sa
----

=== Ingress (L7 - ALB) workload

==== Using kubectl

===== Install

[source,shell]
----
# installs all resources into game-2048 namespace
kubectl apply -f workload-alb-full.yaml

# use this if you want to install this into default profile instead
kubectl apply -f workload-alb-default-ns-full.yaml
----

===== List all resources

[source,shell]
----
kubectl get all -A
----

===== Get Ingresses

[source,shell]
----
kubectl get ing -A
----

Access url via

[source,shell]
----
# for game-2048 namespace
curl -v -k $(kubectl get ing ingress-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# for default namespace
curl -v -k $(kubectl get ing ingress-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# or

# get ingress_url

# for game-2048 namespace
kubectl get ing ingress-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# for default namespace
kubectl get ing ingress-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# and access
curl -v -k ingress_url
----

or access it in browser

===== Uninstall

[source,shell]
----
# for game-2048 namespace
kubectl delete -f workload-alb-full.yaml

# for default namespace
kubectl delete -f workload-alb-default-ns-full.yaml
----

==== Using helm

===== Install

[source,shell]
----
# installs all resources into game-2048 namespace
helm upgrade --install workload workload-alb-chart

# use this if you want to install this into default profile instead
helm upgrade --install workload workload-alb-chart --set defaultNamespace=true
----

===== List all resources

[source,shell]
----
kubectl get all -A
----

===== Get Ingress resources

[source,shell]
----
kubectl get ing -A
----

Access url via

[source,shell]
----
# for game-2048 namespace
curl -v -k $(kubectl get ing ingress-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# for default namespace
curl -v -k $(kubectl get ing ingress-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# or

# get ingress_url

# for game-2048 namespace
kubectl get ing ingress-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# for default namespace
kubectl get ing ingress-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# and access
curl -v -k ingress_url
----

or access it in browser

===== Uninstall

[source,shell]
----
helm uninstall workload
----

=== Service LoadBalancer (L4 - NLB) workload

==== Using kubectl

===== Install

[source,shell]
----
# installs all resources into game-2048 namespace with NLB with target-type: ip
kubectl apply -f workload-nlb-target-type-ip-full.yaml

# installs all resources into game-2048 namespace with NLB with target-type: instance
kubectl apply -f workload-nlb-target-type-instance-full.yaml

# use this, for installing into default profile with NLB with target-type: ip
kubectl apply -f workload-nlb-default-ns-target-type-ip-full.yaml

# use this, for installing into default profile with NLB with target-type: instance
kubectl apply -f workload-nlb-default-ns-target-type-instance-full.yaml
----

===== List all resources

[source,shell]
----
kubectl get all -A
----

===== Get Services

[source,shell]
----
kubectl get svc -A
----

Access url via

[source,shell]
----
# for game-2048 namespace
curl -v -k $(kubectl get svc service-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# for default namespace
curl -v -k $(kubectl get svc service-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# or

# get service_url

# for game-2048 namespace
kubectl get svc service-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# for default namespace
kubectl get svc service-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# and access
curl -v -k service_url
----

or access it in browser

===== Uninstall

[source,shell]
----
# for game-2048 namespace with NLB with target-type: ip
kubectl delete -f workload-nlb-target-type-ip-full.yaml

# for game-2048 namespace with NLB with target-type: instance
kubectl delete -f workload-nlb-target-type-instance-full.yaml

# for default namespace with NLB with target-type: ip
kubectl delete -f workload-nlb-default-ns-target-type-ip-full.yaml

# for default namespace with NLB with target-type: instance
kubectl delete -f workload-nlb-default-ns-target-type-instance-full.yaml
----

==== Using helm

===== Install

[source,shell]
----
# installs all resources into game-2048 namespace with NLB with target-type: ip
helm upgrade --install workload workload-nlb-chart

# installs all resources into game-2048 namespace with NLB with target-type: instance
helm upgrade --install workload workload-nlb-chart --set nlbTargetType=instance

# use this, for installing into default profile with NLB with target-type: ip
helm upgrade --install workload workload-nlb-chart --set defaultNamespace=true

# use this, for installing into default profile with NLB with target-type: instance
helm upgrade --install workload workload-nlb-chart  --set nlbTargetType=instance --set defaultNamespace=true
----

===== List all resources

[source,shell]
----
kubectl get all -A
----

===== Get Services

[source,shell]
----
kubectl get svc -A
----

Access url via

[source,shell]
----
# for game-2048 namespace
curl -v -k $(kubectl get svc service-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# for default namespace
curl -v -k $(kubectl get svc service-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname')

# or

# get service_url

# for game-2048 namespace
kubectl get svc service-2048 -n game-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# for default namespace
kubectl get svc service-2048 -o yaml | yq '.status.loadBalancer.ingress[0].hostname'

# and access
curl -v -k service_url
----

or access it in browser

===== Uninstall

[source,shell]
----
helm uninstall workload
----

=== Delete cluster

[source,shell]
----
eksctl delete cluster --name workload
----

== Imperative version

[source,shell]
----
# Create cluster
eksctl create cluster \
    --name workload \
    --region ap-south-1 \
    --version 1.24 \
    --nodegroup-name workload-ng \
    --instance-prefix workload-ng-instance \
    --node-type t3.medium \
    --nodes 2 \
    --nodes-min 2 \
    --nodes-max 2 \
    --max-pods-per-node 100 \
    --node-volume-size 20 \
    --node-volume-type gp2 \
    --node-ami-family Ubuntu2004 \
    --alb-ingress-access

# Enable OIDC with cluster
eksctl utils associate-iam-oidc-provider \
    --region ap-south-1 \
    --cluster workload \
    --approve

# Creat IAM policy for AWS loadbalancer controller
curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json

aws iam create-policy \
    --policy-name AWSLoadBalancerControllerIAMPolicy \
    --policy-document file://iam-policy.json

# List loadbalancer policy & note ARN
aws iam list-policies --query "Policies[?PolicyName == 'AWSLoadBalancerControllerIAMPolicy'].Arn"

# Create service account & link it to AWS IAM policy
eksctl create iamserviceaccount \
    --cluster=workload \
    --namespace=kube-system \
    --name=workload-sa \
    --attach-policy-arn=arn:aws:iam::<account_id>:policy/AWSLoadBalancerControllerIAMPolicy \
    --approve

# Install AWS Load Balancer Controller
helm repo add eks https://aws.github.io/eks-charts

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
    -n kube-system \
    --set clusterName=workload \
    --set serviceAccount.create=false \
    --set serviceAccount.name=workload-sa

####
# For instructions on launching & cleaning up Ingress (L7 - ALB) workload, look back at above section named:
#     Ingress (L7 - ALB) workload
# For instructions on launching & cleaning up Service LoadBalancer (L4 - NLB) based workload, look back at above section named:
#     Service LoadBalancer (L4 - NLB) workload
####

####
# Next section DELETES resources, proceed with CAUTION
# For final cleanup follow subsequent steps
####

# List loadbalancer policy & note ARN
aws iam list-policies --query "Policies[?PolicyName == 'AWSLoadBalancerControllerIAMPolicy'].Arn"

# Delete loadbalancer policy
aws iam delete-policy \
    --policy-arn arn:aws:iam::<account_id>:policy/AWSLoadBalancerControllerIAMPolicy

# Delete service account
#eksctl delete iamserviceaccount \
#    --cluster=workload \
#    --namespace=kube-system \
#    --name=workload-sa

# Delete cluster
eksctl delete cluster --name workload
----

== References

Read more at

. https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html[Network load balancing on Amazon EKS]
. https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[Application load balancing on Amazon EKS]
. https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller[AWS Load Balancer Controller]
