= Readme

Launch EKS cluster using `eksctl`, Install a workload into cluster via ALB Ingress.

You need to install

. kubectl[https://kubectl.docs.kubernetes.io/]
. helm[https://helm.sh/docs/intro/install/]
. aws-cli[https://github.com/aws/aws-cli]
. eksctl[https://eksctl.io/]

It installs AWS Load Balancer controller (This is AWS LoadBalancer, not Application LoadBalancer). AWS LoadBalancer is refers to all load balancers --- Application LoadBalancer (ALB), Network LoadBalancer (NLB) & Elastic LoadBalancer (ELB) i.e AWS LB ≠ ALB, AWS LB = ALB &/ NLB &/ ELB.

== Quasi-Declarative version

=== Create cluster

[source,shell]
----
eksctl create cluster -f eksctl-workload-cluster.yml
----

=== Install Ingress CRDs

[source,shell]
----
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master" --dry-run='server'

kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
----

=== Install AWS Load Balancer Controller

[source,shell]
----
helm repo add eks https://aws.github.io/eks-charts

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
    -n kube-system \
    --set clusterName=workload \
    --set serviceAccount.create=false \
    --set serviceAccount.name=workload-sa
----

=== Install workload (using kubectl)

[source,shell]
----
kubectl apply -f workload-full.yaml
----

=== List all resources

[source,shell]
----
kubectl get all -A
----

=== Get Ingress resource

[source,shell]
----
kubectl get ing -A
----

Access url via

[source,shell]
----
curl -v -k <ing_url>
----

or in browser

=== Uninstall workload

[source,shell]
----
kubectl delete -f workload-full.yaml
----

=== Install workload (using helm)

[source,shell]
----
helm upgrade --install workload workload-chart
----

=== Uninstall workload

[source,shell]
----
helm uninstall workload
----

=== Delete cluster

[source,shell]
----
eksctl delete cluster --name workload
----

== Imperative version

[source,shell]
----
# Create cluster
eksctl create cluster \
    --name workload \
    --region ap-south-1 \
    --version 1.24 \
    --nodegroup-name workload-ng \
    --instance-prefix workload-ng-instance \
    --node-type t3.medium \
    --nodes 2 \
    --nodes-min 2 \
    --nodes-max 2 \
    --max-pods-per-node 100 \
    --node-volume-size 20 \
    --node-volume-type gp2 \
    --node-ami-family Ubuntu2004 \
    --alb-ingress-access

# Enable OIDC with cluster
eksctl utils associate-iam-oidc-provider \
    --region ap-south-1 \
    --cluster workload \
    --approve

# Creat IAM policy for AWS loadbalancer controller
curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json

aws iam create-policy \
    --policy-name AWSLoadBalancerControllerIAMPolicy \
    --policy-document file://iam-policy.json

# List loadbalancer policy & note ARN
aws iam list-policies --query "Policies[?PolicyName == 'AWSLoadBalancerControllerIAMPolicy'].Arn"

# Create service account & link it to AWS IAM policy
eksctl create iamserviceaccount \
    --cluster=workload \
    --namespace=kube-system \
    --name=workload-sa \
    --attach-policy-arn=arn:aws:iam::<account_id>:policy/AWSLoadBalancerControllerIAMPolicy \
    --approve

# Install AWS Load Balancer Controller
helm repo add eks https://aws.github.io/eks-charts

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
    -n kube-system \
    --set clusterName=workload \
    --set serviceAccount.create=false \
    --set serviceAccount.name=workload-sa

# Install workload (using kubectl)
kubectl apply -f workload-full.yaml

# List all resources
kubectl get all -A

# Get Ingress resource
kubectl get ing -A

# (or) Access url via
curl -v -k ing_url
# or in browser

# Uninstall workload
kubectl delete -f workload-full.yaml

# Install workload (using helm)
helm upgrade --install workload workload-chart

# Uninstall workload
helm uninstall workload

# List loadbalancer policy & note ARN
aws iam list-policies --query "Policies[?PolicyName == 'AWSLoadBalancerControllerIAMPolicy'].Arn"

# Delete loadbalancer policy
aws iam delete-policy \
    --policy-arn arn:aws:iam::<account_id>:policy/AWSLoadBalancerControllerIAMPolicy

# Delete service account
#eksctl delete iamserviceaccount \
#    --cluster=workload \
#    --namespace=kube-system \
#    --name=workload-sa

# Delete cluster
eksctl delete cluster --name workload
----

== References

Read more about this https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller[AWS Load Balancer Controller]
