apiVersion: v1
kind: Service
metadata:
  {{- if not (.Values.defaultNamespace) }}
  namespace: game-2048
  {{- end }}
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048
